### ISSUE TITLE
Copyright claim in Readme.md

### ISSUE THREAD

**Issue by wrznr** [ediarum/ediarum.BASE.edit#2]
Many thanks for the shiny new `ediarum` repository. Great work!

A tiny issue:
I wonder what the copyright claim in the Readme is for. Do I have to ask for your permission before cloning or forking this project (i.e. making a **copy**)? This would contradict with the LICENSE you set up for this repository. Or maybe it is the Readme itself which is subject to copy restrictions? However, I am pretty sure that a LICENSE file must/does apply to all files in a repository.

**Comment by StefanDumont** [comment]
Hi @wrznr,
of course the GPL apply to all files in this repository. The Copyright notice on top of the files (and even the readme) is obligatory for GPL licenced files. See the GPL documentation:

> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each past release; for example, “Copyright 1998, 1999 Terry Jones” if some releases were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.
> 
> For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.
> 
> Always use the English word “Copyright”; by international convention, this is used worldwide, even for material in other languages. The copyright symbol “©” can be included if you wish (and your character set supports it), but it's not necessary. There is no legal significance to using the three-character sequence “(C)”, but it does no harm.
> 
> If you have copied code from other programs covered by the same license, copy their copyright notices too. Put all the copyright notices for a file together, right near the top of the file.

https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by wrznr** [comment]
I didn't knew that. Interesting. Maybe I should start to read the licenses I use before applying them. Many thanks.
